### PR TITLE
Mark bundle as ezplatform-bundle

### PR DESCRIPTION
**Pull request by MarioBlazek**
Makes it possible to query ezplatform bundles via packagist: https://packagist.org/packages/list.json?type=ezplatform-bundle

### CODE REVIEW

**Comment by gggeek** [comment]
Yup.
I seem to have forgotten where it is documented that that is the correct type to use ?

**Comment by MarioBlazek** [comment]
FYI https://github.com/netgen/TagsBundle/pull/53

**Comment by MarioBlazek** [comment]
@gggeek should I close this PR ?

**Comment by gggeek** [comment]
No need, you can leave it open until it gets fixed one day. I don't mind open issues :-)

**Pull request closed without merging**
